### PR TITLE
[9.0] improve the way crons are fetching files

### PR DESCRIPTION
**Pull request by umiphos**
There are several issues right now in this PR:

1. The way we retrieve the zip from sunat is not the best, urllib is taking so much time to retrieve a small dummy file that I doubt that the cron will ever do any job at all before a timeout

2. One cron to do all the work is not the best, we should retrieve the file one time and in another non related time process it's data

3. The method that retrieves the zip shall be configurable by URL in the method, otherwise we will need (in the event of the change of URL by sunat) to change that said URL each time.

4. We need a .travis.yml in this little app with the postgresql that we know works well

### urllib is no good

[](https://youtu.be/mBujP-9ZcmA "Soy un vidio :smile_cat: Danos manito arriba, comparte y suscribete y pasalo por whats ;)  ")

### CODE REVIEW

**Comment by cowardvassal** [comment]
**WARNING**: Could not create a deploy configuration. Task ID not found in the title of the PR, supported formats:

```
{ task type }#{ number }
{ task type }{ number }
```
Available task types: task, t, vx, issue, i, us, hu _(case insensitive)_
_Examples_: 

- task#123

- Issue123

- US#123

**Comment by cowardvassal** [comment]
**WARNING**: Could not create a deploy configuration. Task ID not found in the title of the PR, supported formats:

```
{ task type }#{ number }
{ task type }{ number }
```
Available task types: task, t, vx, issue, i, us, hu _(case insensitive)_
_Examples_: 

- task#123

- Issue123

- US#123

**Comment by umiphos** [comment]
@josemoralesp this is working, I recommend you to use a dummy zip in order to test it, because processing the 12M registers at once takes 2:30 hrs...

**Comment by josemoralesp** [comment]
Hello @umiphos 
This change looks good to me. But this change requires a change in the modules which use this feature.

Right now I can remember l10n_pe_vat_sunat_validation located in odoo_peru. 

You must remove these lines:
[1] https://github.com/Vauxoo/odoo-peru/blob/10.0/l10n_pe_vat_sunat_validation/tests/test_auto_fill.py#L26
[2] https://github.com/Vauxoo/odoo-peru/blob/10.0/l10n_pe_vat_sunat_validation/tests/test_auto_fill.py#L29
[3] https://github.com/Vauxoo/odoo-peru/blob/10.0/l10n_pe_vat_sunat_validation/models/res_partner.py#L31
[4] https://github.com/Vauxoo/odoo-peru/blob/10.0/l10n_pe_vat_sunat_validation/data/ir_config_parameter.xml#L9-L12
[5] https://github.com/Vauxoo/odoo-peru/blob/3124b6fa8dda0bdc7435ad845b6bdd918b74bc92/l10n_pe_vat_sunat_validation/demo/ir_config_parameter.xml#L9-L12

If there is another line concerning sunatdb.api_user, do not hesitate to delete it.

Best regards.

**Pull request merged**
